version: '3'

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - storybook-static:/var/www/html/storybook-static/

  nginx:
    depends_on:
      - 'node'
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - storybook-static:/var/www/html/

volumes:
  storybook-static:
